config/routes.rb
Rails.application.routes.draw do
  get 'shops/index'

  resources :card_categories
  
  resources :shops
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  get "home/index" => 'home#index'
  get '/shop_search_result' => "home#shop_search_result"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card_category.rb
class CardCategory < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/shop.rb
class Shop < ApplicationRecord

  geocoded_by :address
  after_validation :geocode
end



  def address
    "#{address}"
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/card_categories_controller.rb
class CardCategoriesController < ApplicationController
  before_action :set_card_category, only: [:show, :edit, :update, :destroy]

  # GET /card_categories
  # GET /card_categories.json
  def index
    @card_categories = CardCategory.all
  end

  # GET /card_categories/1
  # GET /card_categories/1.json
  def show
  @card_category = CardCategory.find(params[:id])
  end

  # GET /card_categories/new
  def new
    @card_category = CardCategory.new
  end

  # GET /card_categories/1/edit
  def edit
    @card_category = CardCategory.find(params[:id])
  end

  # POST /card_categories
  # POST /card_categories.json
  def create
    @card_category = CardCategory.new(card_category_params)

    respond_to do |format|
      if @card_category.save
        format.html { redirect_to @card_category, notice: 'Card category was successfully created.' }
        format.json { render :show, status: :created, location: @card_category }
      else
        format.html { render :new }
        format.json { render json: @card_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /card_categories/1
  # PATCH/PUT /card_categories/1.json
  def update
    respond_to do |format|
      if @card_category.update(card_category_params)
        format.html { redirect_to @card_category, notice: 'Card category was successfully updated.' }
        format.json { render :show, status: :ok, location: @card_category }
      else
        format.html { render :edit }
        format.json { render json: @card_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /card_categories/1
  # DELETE /card_categories/1.json
  def destroy
    @card_category.destroy
    respond_to do |format|
      format.html { redirect_to card_categories_url, notice: 'Card category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card_category
      @card_category = CardCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_category_params
      params.require(:card_category).permit(:name,)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @shops = Shop.last(6)
      respond_to do |format|
      format.html
      format.js
     end 
  end
    

  def shop_search_result
      q = params[:q]
      @near_by_shops = Shop.search(address_cont: q).result
      @lat = params[:shop_search][:latitude].to_f
      @long = params[:shop_search][:longitude].to_f
      distance = params[:shop_search][:kms].to_i
 	    @near_by_shops = Shop.near([@lat, @long], distance, units: :km) 
  end



  
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
   	@shops = Shop.all
  end
    
  
 
 def show
 	@shop = Shop.find(params[:id])
 end 

 def new
 	@shop = Shop.new
 end

 def edit
 @shop = Shop.find(params[:id])
 end	

 def create
   	@shop = Shop.new(shop_params)
     
   if	@shop.save	
   	redirect_to @shop
   else
   	render 'new'
   end	
 end

 def update
 @shop = Shop.find(params[:id])

 if @shop.update(shop_params)
 	redirect_to @shop
 else
 	render 'edit'
  end	
 end

 def destroy
     @shop = Shop.find(params[:id])
     @shop.destroy

   	redirect_to shops_path
 end	

  private
   def shop_params
   	  params.require(:shop).permit(:name, :address, :latitude, :longitude,)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_categories_helper.rb
module CardCategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/card_categories/_form.html.erb
<%= form_with(model: card_category, local: true) do |form| %>
  <% if card_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card_category.errors.count, "error") %> prohibited this card_category from being saved:</h2>

      <ul>
      <% card_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :cardcategory_name %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/card_categories/edit.html.erb
<h1>Editing Card Category</h1>

<%= render 'form', card_category: @card_category %>

<%= link_to 'Show', @card_category %> |
<%= link_to 'Back', card_categories_path %>

app/views/card_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Card Categories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @card_categories.each do |card_category| %>
      <tr>
        <td><%= card_category.name %></td>
        <td><%= link_to 'Show', card_category %></td>
        <td><%= link_to 'Edit', edit_card_category_path(card_category) %></td>
        <td><%= link_to 'Destroy', card_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card Category', new_card_category_path %>

app/views/card_categories/new.html.erb
<h1>New Card Category</h1>

<%= render 'form', card_category: @card_category %>

<%= link_to 'Back', card_categories_path %>

app/views/card_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>Name:</strong>
    <%= @card_category.name %>
</p>
<%= link_to 'Edit', edit_card_category_path(@card_category) %> |
<%= link_to 'Back', card_categories_path %>

app/views/home/index.html.erb
<%= form_for :shop_search, url: :shop_search_result, method: :get do |f| %>  
<%= f.select :kms, (['5','10','25','75','100']) %>

            <%= f.text_field :location, class: "form-control input-lg", "aria-describedby" => "basic-addon2", id: "autocomplete", placeholder: "Search shops by location",
             onFocus: "geolocate()" %>
            <%= f.hidden_field :latitude, id: :shop_latitude %>
            <%= f.hidden_field :longitude, id: :shop_longitude %>
            <div class="input-group-append">
              <%= f.submit "Search", class: "btn btn-primary btn-lg" %>
            </div>
            <% end %>
             <%  @near_by_shops = Shop.near([22.71, 75.85], 50, units: :km) %>

            <% @near_by_shops.each do |shop| %>
            <h1><%= shop.name %></h1>
          <% end %>
            
             <%= link_to "View all shops", shops_path, class: "btn btn-outline-primary btn-lg" %>

        
<script>
  var placeSearch, autocomplete;
  var componentForm = {
    street_number: 'short_name',
    route: 'long_name',
    locality: 'long_name',
    administrative_area_level_1: 'short_name',
    country: 'long_name',
    postal_code: 'short_name',
  };

  function initAutocomplete() {
    autocomplete = new google.maps.places.Autocomplete(
      (document.getElementById('autocomplete')),
        {types: ['geocode']});

    autocomplete.addListener('place_changed', fillInAddress);
  }

  function fillInAddress() {
    var place = autocomplete.getPlace();
    lat = place.geometry.location.lat();
    long = place.geometry.location.lng();
    $("#shop_latitude").val(lat);
    $("#shop_longitude").val(long);

    for (var component in componentForm) {
      document.getElementById(component).value = '';
      document.getElementById(component).disabled = false;
    }
    for (var i = 0; i < place.address_components.length; i++) {
      var addressType = place.address_components[i].types[0];
      if (componentForm[addressType]) {
        var val = place.address_components[i][componentForm[addressType]];
        document.getElementById(addressType).value = val;
      }
    }
  }
  
  function geolocate() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        var geolocation = {
          lat: position.coords.latitude,
          lng: position.coords.longitude
        };
        var circle = new google.maps.Circle({
          center: geolocation,
          radius: position.coords.accuracy
        });
        autocomplete.setBounds(circle.getBounds());
      });
    }
  }
</script>


<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCCGG6jVWyZDiUH3DD6YQLxGcmLlP5V6FA&libraries=places&callback=initAutocomplete"
        async defer></script>
<br>

app/views/home/shop_search_result.html.erb
<% @near_by_shops.each do |shop| %>  
<h6><%= shop.name %></h6>
<h6><%= shop.address %></h6>
<%= link_to shop_path(shop), class: "btn btn-primary" do %>show
<% end %>
 <% end %>
 <br>

 <div class="col-md-5">
      <div id="map" style="width:100%;height:500px;"></div>
    </div>
  </div>
</div>

 <!-- <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyAC1cqAmyA4B5g45X12AYT61H3XLUzUQxs"></script>  -->
      <b><p id="demo"></p></b>


 <script type="text/javascript">
 var im = 'http://www.robotwoods.com/dev/misc/bluecircle.png';

        var x = document.getElementById("demo");
        if (navigator.geolocation){
          navigator.geolocation.getCurrentPosition(showCurrentLocation);
        }
        else{
          alert("Geolocation API not supported.");
        }

        function showCurrentLocation(position){
          var address = position.coords.address;
          var latitude = position.coords.latitude;
          var longitude = position.coords.longitude;
          var coords = new google.maps.LatLng(latitude, longitude, address);
          
          /*x.innerHTML="Latitude: " + position.coords.latitude + 
          "<br>Longitude: " + position.coords.longitude + 
          "<br>address: " + position.coords.address;
*/    //
        var mapOptions = {
      zoom: 15,
      center: coords,
      mapTypeControl: true,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };

  var locations = [];

  <% @near_by_shops.each do |shop| %>
    locations.push(["<%= shop.name %>", <%= shop.latitude %>, <%= shop.longitude %>])
  <% end %>



  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 11,
    center: new google.maps.LatLng(locations[0][1], locations[0][2]),
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });

  var marker = new google.maps.Marker({
              position: coords,
              map: map,
              icon: im
            });
    
  var infowindow = new google.maps.InfoWindow();

  var marker, i;

  for (i = 0; i < locations.length; i++) {  
    marker = new google.maps.Marker({
      position: new google.maps.LatLng(locations[i][1], locations[i][2]),
      map: map
    });

    google.maps.event.addListener(marker, 'click', (function(marker, i) {
      return function() {
        infowindow.setContent(locations[i][0]);
        infowindow.open(map, marker);
      }
    })(marker, i));
  }}

</script>
<script 
  async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAC1cqAmyA4B5g45X12AYT61H3XLUzUQxs&callback=initMap">
</script>
<br>


<!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
 --><!-- <link rel="stylesheet" href="/resources/demos/style.css"> -->
<!--  <style>
  #slider{
    margin-top:40% ; 
    width:40em;
  }
  #custom-handle{
    width: 2em;
    height: 1.6em;
    top: 50%;
    margin-top: -.8em;
    text-align: center;
    line-height: 1.6em;
  }
</style>
             
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script> 
  $( function() {
    var handle = $( "#custom-handle" );
    $( "#slider" ).slider({

      create: function() {
        handle.text( $( this ).slider( "value" ) );
      },
      slide: function( event, ui ) {
        
        handle.text( ui.value );
      }
    });
  } );


  </script>


<body>
      <div id = "slider" >
        <div id="custom-handle" class="ui-slider-handle"></div>
      </div>

</body>
 -->

<!-- <script type="text/javascript">
  $("#internal_btn").click(function() {
            //window.alert("clicked internal btn!");
            $.ajax({
                type: "GET",
               
                url: "/shop_search_result",
                
                
      
        });
</script> -->


<%= form_for :shop_search, url: :shop_search_result, method: :get , :remote=>true do |f| %>  

 <%= f.hidden_field :latitude, value: @lat %>
  <%= f.hidden_field :longitude, value: @long %>
<%= f.range_field :kms , onchange: 'this.form.submit();' , id:"slider1" %>

<%end %>
<%  @near_by_shops = Shop.near([@lat, @long], 50, units: :km) %>








<link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css"
         rel = "stylesheet">
      <script src = "https://code.jquery.com/jquery-1.10.2.js"></script>
      <script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

      <!-- Javascript -->
      <script>
         $(function() {
            $( "#slider" ).slider();
         });
      </script>
   </head>
   <div id="demo"></div>
      <div id = "slider" style="width: 500px"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/myapp1.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myapp1" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Myapp1</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/shops/_form.html.erb
<%= form_for @shop, :html => { :class => "form-horizontal shop" } do |f| %>

  <% if @shop.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @shop.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
     <%= f.text_field :address, class: "form-control input-lg", "aria-describedby" => "basic-addon2", id: "autocomplete", placeholder: "Search shops by location",
             onFocus: "geolocate()" %>
    </div>
    <%=f.error_span(:address) %>
  </div>
  <div class="form-group">
    
    <div class="col-lg-10">
      <%= f.hidden_field :latitude, :class => 'form-control' %>
    </div>
    <%=f.error_span(:latitude) %>
  </div>
  <div class="form-group">
    
    <div class="col-lg-10">
      <%= f.hidden_field :longitude, :class => 'form-control' %>
    </div>
    <%=f.error_span(:longitude) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                shops_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>


<script>
  var placeSearch, autocomplete;
  var componentForm = {
    street_number: 'short_name',
    route: 'long_name',
    locality: 'long_name',
    administrative_area_level_1: 'short_name',
    country: 'long_name',
    postal_code: 'short_name',
  };

  function initAutocomplete() {
    autocomplete = new google.maps.places.Autocomplete(
      (document.getElementById('autocomplete')),
        {types: ['geocode']});

    autocomplete.addListener('place_changed', fillInAddress);
  }

  function fillInAddress() {
    var place = autocomplete.getPlace();
    lat = place.geometry.location.lat();
    long = place.geometry.location.lng();
    $("#shop_latitude").val(lat);
    $("#shop_longitude").val(long);

    for (var component in componentForm) {
      document.getElementById(component).value = '';
      document.getElementById(component).disabled = false;
    }
    for (var i = 0; i < place.address_components.length; i++) {
      var addressType = place.address_components[i].types[0];
      if (componentForm[addressType]) {
        var val = place.address_components[i][componentForm[addressType]];
        document.getElementById(addressType).value = val;
      }
    }
  }
  
  function geolocate() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        var geolocation = {
          lat: position.coords.latitude,
          lng: position.coords.longitude
        };
        var circle = new google.maps.Circle({
          center: geolocation,
          radius: position.coords.accuracy
        });
        autocomplete.setBounds(circle.getBounds());
      });
    }
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCCGG6jVWyZDiUH3DD6YQLxGcmLlP5V6FA&libraries=places&callback=initAutocomplete"
        async defer></script>
<br>

app/views/shops/edit.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/shops/index.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:latitude) %></th>
      <th><%= model_class.human_attribute_name(:longitude) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= link_to shop.id, shop_path(shop) %></td>
        <td><%= shop.name %></td>
        <td><%= shop.address %></td>
        <td><%= hidden_field :latitude, id: :shop_latitude %></td>
        <td><%= hidden_field :longitude, id: :shop_longitude %></td>
        <td><%=l shop.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      shop_path(shop), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_shop_path(shop), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      shop_path(shop),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_shop_path,
            :class => 'btn btn-primary' %>

app/views/shops/new.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/shops/show.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @shop.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @shop.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:latitude) %>:</strong></dt>
  <dd><%= @shop.latitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longitude) %>:</strong></dt>
  <dd><%= @shop.longitude %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              shops_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_shop_path(@shop), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              shop_path(@shop),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>





<div id="map_canvas" style="width:50%;height:500px;"></div> 
<script>
function initMap() {
  var myLatLng = {lat: <%= @shop.latitude %>, lng: <%= @shop.longitude %>};

  var map = new google.maps.Map(document.getElementById('map_canvas'), {
    zoom: 12,
    center: myLatLng
  });

  var marker = new google.maps.Marker({
    position: myLatLng,
    map: map,
    title: 'Hello World!'
  });
}
</script>
<script 
  async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAC1cqAmyA4B5g45X12AYT61H3XLUzUQxs&callback=initMap">
</script>